version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: MusicService
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgrespw"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    ports:
      - "80:8080"
    volumes:
      - ./doc:/usr/share/nginx/html/doc
    environment:
      API_URL: doc/openapi.yaml
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    volumes:
      - redis-data:/data
volumes:
  redis-data:
    driver: local