// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: internal/protos/MusicService.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MusicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *MusicRequest) Reset() {
	*x = MusicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_MusicService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MusicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MusicRequest) ProtoMessage() {}

func (x *MusicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_MusicService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MusicRequest.ProtoReflect.Descriptor instead.
func (*MusicRequest) Descriptor() ([]byte, []int) {
	return file_internal_protos_MusicService_proto_rawDescGZIP(), []int{0}
}

func (x *MusicRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type MetaData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename  string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Extension string `protobuf:"bytes,2,opt,name=extension,proto3" json:"extension,omitempty"`
}

func (x *MetaData) Reset() {
	*x = MetaData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_MusicService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaData) ProtoMessage() {}

func (x *MetaData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_MusicService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaData.ProtoReflect.Descriptor instead.
func (*MetaData) Descriptor() ([]byte, []int) {
	return file_internal_protos_MusicService_proto_rawDescGZIP(), []int{1}
}

func (x *MetaData) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *MetaData) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

type AddMusicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//
	//	*AddMusicRequest_Metadata
	//	*AddMusicRequest_ChunkData
	Request isAddMusicRequest_Request `protobuf_oneof:"request"`
}

func (x *AddMusicRequest) Reset() {
	*x = AddMusicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_MusicService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMusicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMusicRequest) ProtoMessage() {}

func (x *AddMusicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_MusicService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMusicRequest.ProtoReflect.Descriptor instead.
func (*AddMusicRequest) Descriptor() ([]byte, []int) {
	return file_internal_protos_MusicService_proto_rawDescGZIP(), []int{2}
}

func (m *AddMusicRequest) GetRequest() isAddMusicRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *AddMusicRequest) GetMetadata() *MetaData {
	if x, ok := x.GetRequest().(*AddMusicRequest_Metadata); ok {
		return x.Metadata
	}
	return nil
}

func (x *AddMusicRequest) GetChunkData() []byte {
	if x, ok := x.GetRequest().(*AddMusicRequest_ChunkData); ok {
		return x.ChunkData
	}
	return nil
}

type isAddMusicRequest_Request interface {
	isAddMusicRequest_Request()
}

type AddMusicRequest_Metadata struct {
	Metadata *MetaData `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type AddMusicRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*AddMusicRequest_Metadata) isAddMusicRequest_Request() {}

func (*AddMusicRequest_ChunkData) isAddMusicRequest_Request() {}

type RemoveMusicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *RemoveMusicRequest) Reset() {
	*x = RemoveMusicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_MusicService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveMusicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMusicRequest) ProtoMessage() {}

func (x *RemoveMusicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_MusicService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMusicRequest.ProtoReflect.Descriptor instead.
func (*RemoveMusicRequest) Descriptor() ([]byte, []int) {
	return file_internal_protos_MusicService_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveMusicRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type MusicResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *MusicResponse) Reset() {
	*x = MusicResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_MusicService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MusicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MusicResponse) ProtoMessage() {}

func (x *MusicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_MusicService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MusicResponse.ProtoReflect.Descriptor instead.
func (*MusicResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_MusicService_proto_rawDescGZIP(), []int{4}
}

func (x *MusicResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AddMusicResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Url    string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *AddMusicResponse) Reset() {
	*x = AddMusicResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_MusicService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMusicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMusicResponse) ProtoMessage() {}

func (x *AddMusicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_MusicService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMusicResponse.ProtoReflect.Descriptor instead.
func (*AddMusicResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_MusicService_proto_rawDescGZIP(), []int{5}
}

func (x *AddMusicResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *AddMusicResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type RemoveMusicResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *RemoveMusicResponse) Reset() {
	*x = RemoveMusicResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_MusicService_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveMusicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMusicResponse) ProtoMessage() {}

func (x *RemoveMusicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_MusicService_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMusicResponse.ProtoReflect.Descriptor instead.
func (*RemoveMusicResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_MusicService_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveMusicResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_internal_protos_MusicService_proto protoreflect.FileDescriptor

var file_internal_protos_MusicService_proto_rawDesc = []byte{
	0x0a, 0x22, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x47, 0x52, 0x50, 0x43, 0x22, 0x22, 0x0a, 0x0c, 0x4d, 0x75,
	0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x44,
	0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x78, 0x74, 0x65, 0x6e,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0x6b, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x4d, 0x75, 0x73, 0x69, 0x63,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x47, 0x52, 0x50, 0x43,
	0x2e, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1f, 0x0a, 0x0a, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x09, 0x63, 0x68, 0x75,
	0x6e, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x42, 0x09, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x28, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x75, 0x73, 0x69, 0x63,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x21, 0x0a, 0x0d, 0x4d,
	0x75, 0x73, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x3c,
	0x0a, 0x10, 0x41, 0x64, 0x64, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x2d, 0x0a, 0x13,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0xc7, 0x01, 0x0a, 0x05,
	0x4d, 0x75, 0x73, 0x69, 0x63, 0x12, 0x39, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x4d, 0x75, 0x73, 0x69, 0x63, 0x12, 0x12, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x2e, 0x4d, 0x75, 0x73,
	0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x47, 0x52, 0x50, 0x43,
	0x2e, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x3d, 0x0a, 0x08, 0x61, 0x64, 0x64, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x12, 0x15, 0x2e, 0x47,
	0x52, 0x50, 0x43, 0x2e, 0x41, 0x64, 0x64, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x2e, 0x41, 0x64, 0x64, 0x4d, 0x75,
	0x73, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x12,
	0x44, 0x0a, 0x0b, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x12, 0x18,
	0x2e, 0x47, 0x52, 0x50, 0x43, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x75, 0x73, 0x69,
	0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x2e,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_internal_protos_MusicService_proto_rawDescOnce sync.Once
	file_internal_protos_MusicService_proto_rawDescData = file_internal_protos_MusicService_proto_rawDesc
)

func file_internal_protos_MusicService_proto_rawDescGZIP() []byte {
	file_internal_protos_MusicService_proto_rawDescOnce.Do(func() {
		file_internal_protos_MusicService_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_protos_MusicService_proto_rawDescData)
	})
	return file_internal_protos_MusicService_proto_rawDescData
}

var file_internal_protos_MusicService_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_protos_MusicService_proto_goTypes = []interface{}{
	(*MusicRequest)(nil),        // 0: GRPC.MusicRequest
	(*MetaData)(nil),            // 1: GRPC.MetaData
	(*AddMusicRequest)(nil),     // 2: GRPC.AddMusicRequest
	(*RemoveMusicRequest)(nil),  // 3: GRPC.RemoveMusicRequest
	(*MusicResponse)(nil),       // 4: GRPC.MusicResponse
	(*AddMusicResponse)(nil),    // 5: GRPC.AddMusicResponse
	(*RemoveMusicResponse)(nil), // 6: GRPC.RemoveMusicResponse
}
var file_internal_protos_MusicService_proto_depIdxs = []int32{
	1, // 0: GRPC.AddMusicRequest.metadata:type_name -> GRPC.MetaData
	0, // 1: GRPC.Music.requestMusic:input_type -> GRPC.MusicRequest
	2, // 2: GRPC.Music.addMusic:input_type -> GRPC.AddMusicRequest
	3, // 3: GRPC.Music.removeMusic:input_type -> GRPC.RemoveMusicRequest
	4, // 4: GRPC.Music.requestMusic:output_type -> GRPC.MusicResponse
	5, // 5: GRPC.Music.addMusic:output_type -> GRPC.AddMusicResponse
	6, // 6: GRPC.Music.removeMusic:output_type -> GRPC.RemoveMusicResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_protos_MusicService_proto_init() }
func file_internal_protos_MusicService_proto_init() {
	if File_internal_protos_MusicService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_protos_MusicService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MusicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_MusicService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_MusicService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddMusicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_MusicService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveMusicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_MusicService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MusicResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_MusicService_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddMusicResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_MusicService_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveMusicResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_protos_MusicService_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*AddMusicRequest_Metadata)(nil),
		(*AddMusicRequest_ChunkData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_protos_MusicService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protos_MusicService_proto_goTypes,
		DependencyIndexes: file_internal_protos_MusicService_proto_depIdxs,
		MessageInfos:      file_internal_protos_MusicService_proto_msgTypes,
	}.Build()
	File_internal_protos_MusicService_proto = out.File
	file_internal_protos_MusicService_proto_rawDesc = nil
	file_internal_protos_MusicService_proto_goTypes = nil
	file_internal_protos_MusicService_proto_depIdxs = nil
}
